-- Task 3-- 

use techshop;

-- 1. retrieve a list of all orders along with customer information 
 
select  Orders.OrderID, Customers.FirstName, Customers.LastName, Orders.OrderDate, Orders.TotalAmount
from  Orders
join Customers ON Orders.CustomerID = Customers.CustomerID;

-- 2. total revenue generated by each electronic gadget product

select  Products.ProductName, SUM(OrderDetails.Quantity * Products.Price) AS TotalRevenue
from OrderDetails
join  Products ON OrderDetails.ProductID = Products.ProductID
where  Products.ProductName IN ("Laptop","Smartphone","Tablet","Smartwatch","phone","Keyboard","Mouse","Monitor","Printer","Camera","Bluetooth Speaker")  
group by Products.ProductName;


-- 3. List all customers who have made at least one purchase 

select distinct Customers.FirstName, Customers.LastName, Customers.Email, Customers.Phone, Customers.Address
from  Customers
join Orders ON Customers.CustomerID = Orders.CustomerID;


-- 4. Find the most popular electronic gadget

select  Products.ProductName, SUM(OrderDetails.Quantity) AS TotalQuantityOrdered
from  OrderDetails
join Products ON OrderDetails.ProductID = Products.ProductID
where Products.ProductName IN ("Laptop","Smartphone","Tablet","Smartwatch","phone","Keyboard","Mouse","Monitor","Printer","Camera","Bluetooth Speaker")  
group by  Products.ProductName
order by  TotalQuantityOrdered DESC
LIMIT 1;


-- 5.Retrieve a list of electronic gadgets ( corresponding category)

alter table Products
add  Category VARCHAR(100);

SET SQL_SAFE_UPDATES = 0;
update Products
set Category = 'Electronic Gadgets'
where  ProductName IN ('Laptop', 'Smartphone', 'Tablet', 'Smartwatch', 'phone', 'Keyboard', 'Mouse', 'Monitor', 'Printer', 'Camera', 'Bluetooth Speaker');

select  ProductName, Category
from Products
where  Category = 'Electronic Gadgets';


-- 6. Calculate the average order value for each customer

select  Customers.FirstName, Customers.LastName, AVG(Orders.TotalAmount) AS AverageOrderValue
from  Orders
join Customers ON Orders.CustomerID = Customers.CustomerID
group by Customers.CustomerID;


-- 7. Find the order with the highest total revenue

select Orders.OrderID, Customers.FirstName, Customers.LastName, Orders.TotalAmount
from  Orders
join  Customers ON Orders.CustomerID = Customers.CustomerID
order by  Orders.TotalAmount DESC
LIMIT 1;


-- 8. List electronic gadgets and the number of times each product has been ordered

select  Products.ProductName, COUNT(OrderDetails.OrderDetailID) AS TimesOrdered
from OrderDetails
join  Products ON OrderDetails.ProductID = Products.ProductID
where Products.ProductName IN ("Laptop","Smartphone","Tablet","Smartwatch","phone","Keyboard","Mouse","Monitor","Printer","Camera","Bluetooth Speaker")   
group by  Products.ProductName;


-- 9.  Find customers who have purchased a specific electronic gadget product

select Customers.FirstName, Customers.LastName, Customers.Email, Customers.Phone
from  OrderDetails
join Orders ON OrderDetails.OrderID = Orders.OrderID
join Customers ON Orders.CustomerID = Customers.CustomerID
join  Products ON OrderDetails.ProductID = Products.ProductID
where  Products.ProductName = 'Smartphone';  


-- 10. Calculate the total revenue generated by all orders placed within a specific time period 

select  SUM(Orders.TotalAmount) AS TotalRevenue
from  Orders
where Orders.OrderDate between '2024-01-01' and  '2024-12-31'; 

