-- Task 4 -- 

-- 1. find out which customers have not placed any orders.
select  Customers.CustomerID, Customers.FirstName, Customers.LastName from Customers
where  Customers.CustomerID not in ( select Orders.CustomerID from Orders);

-- 2. Total number of products available for sale.
select (select COUNT(*) from Products) as Total_Products;

-- 3. Calculate the total revenue generated by TechShop
select  (select SUM(Orders.TotalAmount) from Orders) as TotalRevenue;

-- 4.Calculate the average quantity ordered for products in a specific category
select avg(Quantity) from  OrderDetails
where ProductID in ( select ProductID from  Products where Products.Category = 'Electronics' 
);

-- 5.Calculate the total revenue generated by a specific customer
select (sum(orders.TotalAmount)) from orders where orders.customerID = "1";

-- 6.Find the customers who have placed the most orders  (List their names and the number of orders they've placed)
select customers.FirstName, customers.LastName, count(orders.orderID) from customers 
inner join orders on customers.customerID = orders.orderID 
group by Customers.CustomerID, Customers.FirstName, Customers.LastName
order by count(orders.orderID) DESC;


-- 7. find the most popular product category, which is the one with the highest total quantity ordered across all orders.
select Products.Category, SUM(OrderDetails.Quantity)
from  OrderDetails
join  Products ON OrderDetails.ProductID = Products.ProductID
group by  Products.Category
order by SUM(OrderDetails.Quantity) DESC
LIMIT 1;


-- 8. Find the customer who has spent the most money on electronic gadgets.
select customers.firstname, customers.lastname, sum(orders.totalamount) from customers
join orders on customers.customerid = orders.customerid
join orderdetails on orders.orderid = orderdetails.orderid
join products on orderdetails.productid = products.productid
where products.category = 'Electronics'
group by customers.customerid, customers.firstname, customers.lastname
order by sum(orders.totalamount) desc
limit 1;

-- 9.calculate the average order value
select avg(Orders.TotalAmount) from Orders;

-- Alternate way 
select sum(orders.totalAmount)/count(orders.orderID) from orders;

-- 10.  find the total number of orders placed by each customer and list their  names along with the order count
select  Customers.FirstName, Customers.LastName, COUNT(Orders.OrderID) from Customers
inner join  Orders ON Customers.CustomerID = Orders.CustomerID
group by Customers.CustomerID, Customers.FirstName, Customers.LastName;


